version: '3.6'
services:
  zuul-server:
    build:
      zuul-server/
    image:
      hltspires/zuul-server
    ports:
      - 9000:9000
    depends_on:
      - eureka-server
      - candidaturas-api
      - vagas-api
      - pessoas-api
    environment:
      - EUREKA_INSTANCE_HOSTNAME=zuul-server
      - EUREKA_DEFAULT_ZONE_URL=http://eureka-server:9090/eureka/
    networks:
      - candidaturas-app
  eureka-server:
    build:
      eureka-server/
    image:
      hltspires/eureka-server
    ports:
      - 9090:9090
    networks:
      - candidaturas-app
  candidaturas-api:
    build:
      candidaturas-api/
    image:
      hltspires/candidaturas-api
    ports:
      - 9093:9093
    environment:
      - EUREKA_INSTANCE_HOSTNAME=candidaturas-api
      - EUREKA_DEFAULT_ZONE_URL=http://eureka-server:9090/eureka/
    networks:
      - candidaturas-app
  pessoas-api:
    build:
      pessoas-api/
    image:
      hltspires/pessoas-api
    ports:
      - 9092:9092
    environment:
      - EUREKA_INSTANCE_HOSTNAME=pessoas-api
      - EUREKA_DEFAULT_ZONE_URL=http://eureka-server:9090/eureka/
    networks:
      - candidaturas-app
  vagas-api:
    build:
      vagas-api/
    image:
      hltspires/vagas-api
    ports:
      - 9091:9091
    networks:
      - candidaturas-app
    environment:
      - EUREKA_INSTANCE_HOSTNAME=vagas-api
      - EUREKA_DEFAULT_ZONE_URL=http://eureka-server:9090/eureka/
networks:
  candidaturas-app: