eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
    fetch-registry: true
server:
  port: 9000
spring:
  application:
    name: zuul-server
zuul:
  prefix: /v1
  routes:
    vagas:
      path: /vagas/**
      serviceId: vagas-api
      stripPrefix: false
    pessoas:
      path: /pessoas/**
      serviceId: pessoas-api
      stripPrefix: false
    candidaturas:
      path: /candidaturas/**
      serviceId: candidaturas-api
      stripPrefix: false