eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:9090/eureka/}
    registry-fetch-interval-seconds: 5
server:
  port: 9000
spring:
  application:
    name: zuul-server
zuul:
  prefix: /v1
  routes:
    vagas:
      path: /vagas/**
      serviceId: vagas-api
      stripPrefix: false
    pessoas:
      path: /pessoas/**
      serviceId: pessoas-api
      stripPrefix: false
    candidaturas:
      path: /candidaturas/**
      serviceId: candidaturas-api
      stripPrefix: false