eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
server:
  port: 9091
  servlet:
    context-path: /vagas-api
spring:
  application:
    name: vagas-api
  jackson:
    default-property-inclusion: NON_NULL