eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
server:
  port: 9092
  servlet:
    context-path: /pessoas-api
spring:
  application:
    name: pessoas-api
  jackson:
    default-property-inclusion: NON_NULL